import { Brain, LineChart, User, Zap } from 'lucide-react';
import { Card } from '../ui/card';

export function AboutStory() {
    return (
        <div className="space-y-24">
            {/* Origin Story */}
            <section className="grid md:grid-cols-2 gap-12 items-center animate-in fade-in slide-in-from-bottom-8 duration-700 delay-300">
                <div className="space-y-6">
                    <h2 className="text-3xl font-bold flex items-center gap-3">
                        <User className="text-purple-500" />
                        The Origin Story
                    </h2>
                    <div className="prose prose-invert text-muted-foreground">
                        <p>
                            Hi, I'm <strong>Branislav Lang</strong>. Like many of you, I don't just buy ETFs—I hunt for individual stocks with asymmetric upside.
                        </p>
                        <p>
                            But my research process was broken. I found myself jumping between <strong>eToro</strong> for execution, <strong>Yahoo Finance</strong> for data, <strong>StockTwits</strong> for sentiment, and <strong>ChatGPT</strong> for synthesis. It was inefficient, noisy, and prone to "paralysis by analysis."
                        </p>
                        <p>
                            I built NeuralTicker to solve my own problem. I wanted an AI that didn't just summarize news, but actually <em>did the research for me</em>—uncovering the hidden gems that manual analysis often misses.
                        </p>
                    </div>
                </div>
                <div className="relative group">
                    <div className="absolute inset-0 bg-gradient-to-r from-purple-500 to-pink-500 rounded-2xl blur-xl opacity-20 group-hover:opacity-30 transition-opacity" />
                    <Card className="relative p-8 bg-card/50 backdrop-blur border-border/50 overflow-hidden">
                        <div className="absolute top-0 right-0 p-4 opacity-10">
                            <Brain size={120} />
                        </div>
                        <h3 className="text-lg font-semibold mb-4 text-foreground">The Old Way vs. NeuralTicker</h3>
                        <ul className="space-y-4">
                            <li className="flex items-start gap-3 text-sm text-muted-foreground">
                                <div className="min-w-[24px] h-6 flex items-center justify-center rounded bg-red-500/10 text-red-500">✕</div>
                                <span>Opening 10+ tabs (News, Earnings, Social)</span>
                            </li>
                            <li className="flex items-start gap-3 text-sm text-muted-foreground">
                                <div className="min-w-[24px] h-6 flex items-center justify-center rounded bg-red-500/10 text-red-500">✕</div>
                                <span>Generic "Buy/Sell" ratings without context</span>
                            </li>
                            <li className="flex items-start gap-3 text-sm text-foreground font-medium">
                                <div className="min-w-[24px] h-6 flex items-center justify-center rounded bg-green-500/10 text-green-500">✓</div>
                                <span>One unified "Research Note" generated by Agents</span>
                            </li>
                            <li className="flex items-start gap-3 text-sm text-foreground font-medium">
                                <div className="min-w-[24px] h-6 flex items-center justify-center rounded bg-green-500/10 text-green-500">✓</div>
                                <span>AI Advisor that tells you what to cut & what to add</span>
                            </li>
                        </ul>
                    </Card>
                </div>
            </section>

            {/* The Solution / Core Value */}
            <section className="space-y-12">
                <div className="text-center max-w-3xl mx-auto space-y-4">
                    <h2 className="text-3xl font-bold">Unfair Advantage</h2>
                    <p className="text-muted-foreground text-lg">
                        Most tools give you data. NeuralTicker gives you <span className="text-foreground font-semibold">decisions</span>.
                    </p>
                </div>

                <div className="grid md:grid-cols-3 gap-6">
                    <Card className="p-6 bg-card hover:bg-muted/50 transition-colors border-border/50">
                        <div className="h-12 w-12 rounded-lg bg-purple-500/10 flex items-center justify-center text-purple-500 mb-4">
                            <Brain size={24} />
                        </div>
                        <h3 className="text-lg font-semibold mb-2">Agentic Research</h3>
                        <p className="text-sm text-muted-foreground">
                            Our AI agents autonomously browse the web, extract unstructured data from news, and create daily news digests. They scrutinize 10-K filings and analyze sentiment to produce institutional-grade reports.
                        </p>
                    </Card>

                    <Card className="p-6 bg-card hover:bg-muted/50 transition-colors border-border/50">
                        <div className="h-12 w-12 rounded-lg bg-green-500/10 flex items-center justify-center text-green-500 mb-4">
                            <LineChart size={24} />
                        </div>
                        <h3 className="text-lg font-semibold mb-2">Unified Portfolio</h3>
                        <p className="text-sm text-muted-foreground">
                            Sync positions from multiple brokers manually or via CSV. Our AI Advisor actively monitors your portfolio, giving you precise advice on what to add and what to cut to maximize returns.
                        </p>
                    </Card>

                    <Card className="p-6 bg-card hover:bg-muted/50 transition-colors border-border/50">
                        <div className="h-12 w-12 rounded-lg bg-[#FF6C33]/10 flex items-center justify-center text-[#FF6C33] mb-4">
                            <Zap size={24} />
                        </div>
                        <h3 className="text-lg font-semibold mb-2">High-Conviction Filters</h3>
                        <p className="text-sm text-muted-foreground">
                            Don't scroll through thousands of stocks. Our "No Brainer" and "Strong Buy" filters surface only the assets with the highest probability of alpha.
                        </p>
                    </Card>
                </div>
            </section>
        </div>
    );
}
